
SECRET_KEY_BASE: 114fa7844caad5feff4585fe915c60711c12923764a7e6f4a01f28c9e4ed2cd6ce9ea16fc0246b8f7803edaec8ce0db225dfb0e6d36cc8ad511f8e220540e472

AWS_ACCES_KEY_ID: AKIAIYJ5VPLINOWKJIFA 
AWS_SECRET_ACCESS_KEY: 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 

development:
  FOG_DIRECTORY: playgroundbucket
production:
  FOG_DIRECTORY: playgroundbucket2

